# pandas 

In [1]:
import pandas as pd
import numpy as np

<pre>
create
s  = pd.Series( ?? ) 
df = pd.DataFrame( ?? )   -- np.array, dict, list[]  list[{}]

## Series
    data= list or array,  
    index=None,  
    dtype: Dtype | None = None, 
    name=None, 

In [3]:
mylist = [1,2,3,'A', np.nan]
s = pd.Series(data=mylist, index=range(5), name="seq")
s

0      1
1      2
2      3
3      A
4    NaN
Name: seq, dtype: object

In [23]:
mylist = [1,2,3,'A', np.nan]
myarr = np.array( mylist ) 
s = pd.Series(data=myarr, index=range(5), name="seq")
print(s)
print( s.shape )
print( "row갯수:", len(s) )

0      1
1      2
2      3
3      A
4    nan
Name: seq, dtype: object
(5,)
row갯수: 5


<font color=red><b>(5,) 주의주의주의 : 1행5열

In [11]:
mylist = [1,2,3,'A', np.nan]
myarr = np.array(mylist)
myarr  # array(['1', '2', '3', 'A', 'nan'], dtype='<U32')
print( myarr)
print( myarr.shape , "주의주의주의 : 1행5열" )

['1' '2' '3' 'A' 'nan']
(5,) 주의주의주의 : 1행5열


shape  
<font color=red><b> shape() 함수XXXX     
<font color=red><b> mylist.shape  리스트는 shape XXXX

In [18]:
mylist = [  [1,2,3],  [10,20,30]   ]
print( mylist )  #[[1, 2, 3], [10, 20, 30]]
# print( mylist.shape)
print( len(mylist) , len(mylist[0])  ) 


myarr = np.array(mylist)
print(myarr)
print(myarr.shape )

[[1, 2, 3], [10, 20, 30]]
2 3
[[ 1  2  3]
 [10 20 30]]
(2, 3)


## DataFrame
<pre>
head() tail() info() shape  describe()  
    data=None,
    index: Axes | None = None,
    columns: Axes | None = None,
    dtype: Dtype | None = None,

### list or array

In [42]:
mylist = [  [1,2,3],  [10,20,30]   ]
myarr = np.array(mylist)

# df = pd.DataFrame(data=myarr)
df = pd.DataFrame(data=mylist, columns=['a','b','c'], index=[10,20])
print( df.shape )
print( "row갯수:", len(df)  )
df

(2, 3)
row갯수: 2


a   b   c
10   1   2   3
20  10  20  30

### series

In [54]:
s = pd.Series([1,2,3,4] )
df = pd.DataFrame(['a','b','c','d'], columns=['code'])
df['seq'] = s
df['sal'] = [100, 200, 300, 400]
df[    ['id', 'pw']    ] =  np.array( [['kim', 11]] * 4 )
df['tel'] = '000'
df

code  seq  sal   id  pw  tel
0    a    1  100  kim  11  000
1    b    2  200  kim  11  000
2    c    3  300  kim  11  000
3    d    4  400  kim  11  000

### list + dict


*  dict에 사용된 키 값이 dataframe의 컬럼명이 된다

In [72]:
listdic = [ {"uid":"kim", "upw": 111} ,
            {"uid":"kim", "upw": 111}   
          ]
df = pd.DataFrame(listdic)
df

uid  upw
0  kim  111
1  kim  111

### list + list

In [74]:
listlist = [ ["kim", 111] ,
            ["kim", 111]   
          ]
df = pd.DataFrame(listlist, columns=['a','b'])
df

a    b
0  kim  111
1  kim  111

## DataFrame 구조 보기

### index

In [60]:
df = pd.DataFrame(['a','b','c','d'], columns=['code'], index=[10,20,30,40])
print ( df.index )
print ( df.index.values )
print ( df.index.values.tolist() )

Int64Index([10, 20, 30, 40], dtype='int64')
[10 20 30 40]
[10, 20, 30, 40]


In [62]:
df = pd.DataFrame(['a','b','c','d'], columns=['code'])
df.index = [10,20,30,40]
df

code
10    a
20    b
30    c
40    d

### columns

In [66]:
s = pd.Series([1,2,3,4] )
df = pd.DataFrame(['a','b','c','d'], columns=['code'])
df['seq'] = s
df['sal'] = [100, 200, 300, 400]

print ( df.columns )
print ( df.columns.values )
print ( df.columns.values.tolist() )


Index(['code', 'seq', 'sal'], dtype='object')
['code' 'seq' 'sal']
['code', 'seq', 'sal']


### values

In [70]:
s = pd.Series([1,2,3,4] )
df = pd.DataFrame(['a','b','c','d'], columns=['code'])
df['seq'] = s
df['sal'] = [100, 200, 300, 400]

print ( df.values )
print ( df.values.tolist() )

[['a' 1 100]
 ['b' 2 200]
 ['c' 3 300]
 ['d' 4 400]]
[['a', 1, 100], ['b', 2, 200], ['c', 3, 300], ['d', 4, 400]]


### info()  

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 10 to 20
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       2 non-null      int64
 1   b       2 non-null      int64
 2   c       2 non-null      int64
dtypes: int64(3)
memory usage: 64.0 bytes


### head()

In [37]:
# df.head(5)
df.head(1)

a  b  c
10  1  2  3

### tail()

In [38]:
df.tail(1)

a   b   c
20  10  20  30

### describe()

In [40]:
df.describe()

a          b          c
count   2.000000   2.000000   2.000000
mean    5.500000  11.000000  16.500000
std     6.363961  12.727922  19.091883
min     1.000000   2.000000   3.000000
25%     3.250000   6.500000   9.750000
50%     5.500000  11.000000  16.500000
75%     7.750000  15.500000  23.250000
max    10.000000  20.000000  30.000000

# SELECT in DataFrame 

*<font color=red><b>  loc[줄, 칸] : 값으로 꺼내기</font> <br>
*<font color=red><b> iloc[줄, 칸] : 인덱스로 꺼내기 </font>
* [줄, 칸]
    - 단일값
    - [단일값, 단일값, 단일값]
    - 슬라이싱[ : ]

* <font color=red><b> 숫자값에 nan이 있으면 타입은 float(소숫점)

In [85]:
df = pd.read_csv("./lec08_emp.csv", sep="," , parse_dates=['HIREDATE'])
df.head(3)

EMPNO  ENAME       JOB     MGR   HIREDATE   SAL   COMM  DEPTNO
0   7369  SMITH     CLERK  7902.0 1980-12-17   800    NaN      20
1   7499  ALLEN  SALESMAN  7698.0 1981-02-20  1600  300.0      30
2   7521   WARD  SALESMAN  7698.0 1981-02-22  1250  500.0      30

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   EMPNO     14 non-null     int64         
 1   ENAME     14 non-null     object        
 2   JOB       14 non-null     object        
 3   MGR       13 non-null     float64       
 4   HIREDATE  14 non-null     datetime64[ns]
 5   SAL       14 non-null     int64         
 6   COMM      4 non-null      float64       
 7   DEPTNO    14 non-null     int64         
dtypes: datetime64[ns](1), float64(2), int64(3), object(2)
memory usage: 1.0+ KB


### 결측(missing value) 처리
* np.nan
* df1.dropna(axis=1 또는 axis=0)
* df1.fillna(값)
* pd.isna(df1)

In [96]:
dfcp

EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0 1981-02-22  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500     0.0      30

### dropna(axis=0, inplace=True)
* axis = 0 : 행
* axis = 1 : 열

In [99]:
dfcp = df.copy()
# dfcp = dfcp.dropna(axis=0)
dfcp.dropna(axis=0, inplace=True)

In [100]:
dfcp

EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0 1981-02-22  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500     0.0      30

In [2]:
dfcp = df.copy()
# dfcp = dfcp.dropna(axis=0)
dfcp.dropna(axis=1, inplace=True)
dfcp(3)

NameError: name 'df' is not defined

### fillna(inplace=True)
* 결측 채우기 후 일반적으로 형변환을 한다  
*<font color=red><b> df['컬럼'] = df['컬럼'].astype('int')

In [104]:
dfcp = df.copy()
# dfcp = dfcp.fillna(99999)
dfcp.fillna(99999, inplace=True)

In [106]:
dfcp.head(3)

EMPNO  ENAME       JOB     MGR   HIREDATE   SAL     COMM  DEPTNO
0   7369  SMITH     CLERK  7902.0 1980-12-17   800  99999.0      20
1   7499  ALLEN  SALESMAN  7698.0 1981-02-20  1600    300.0      30
2   7521   WARD  SALESMAN  7698.0 1981-02-22  1250    500.0      30

In [116]:
dfcp = df.copy()
# dfcp = dfcp.fillna(99999)
# dfcp['COMM'] = dfcp['COMM'].fillna(8888)
# dfcp['MGR']  = dfcp['MGR'].fillna(77)
dfcp[ ['COMM','MGR'] ] = dfcp[ ['COMM','MGR'] ].fillna(999)
dfcp[ ['COMM','MGR'] ] = dfcp[ ['COMM','MGR'] ].astype('int')
dfcp.head(3)

EMPNO  ENAME       JOB   MGR   HIREDATE   SAL  COMM  DEPTNO
0   7369  SMITH     CLERK  7902 1980-12-17   800   999      20
1   7499  ALLEN  SALESMAN  7698 1981-02-20  1600   300      30
2   7521   WARD  SALESMAN  7698 1981-02-22  1250   500      30

### df.isna() 
* 또는 pd.isna(df)

In [123]:
dfcp = df.copy()
# pd.isna(dfcp)

# dfcp.isna()
# dfcp.notna()

# dfcp.isnull()
# dfcp.notnull()

EMPNO  ENAME   JOB    MGR  HIREDATE   SAL   COMM  DEPTNO
0    True   True  True   True      True  True  False    True
1    True   True  True   True      True  True   True    True
2    True   True  True   True      True  True   True    True
3    True   True  True   True      True  True  False    True
4    True   True  True   True      True  True   True    True
5    True   True  True   True      True  True  False    True
6    True   True  True   True      True  True  False    True
7    True   True  True   True      True  True  False    True
8    True   True  True  False      True  True  False    True
9    True   True  True   True      True  True   True    True
10   True   True  True   True      True  True  False    True
11   True   True  True   True      True  True  False    True
12   True   True  True   True      True  True  False    True
13   True   True  True   True      True  True  False    True

In [3]:
dfcp.info()

NameError: name 'dfcp' is not defined