# **pandas, numpy import**

In [2]:
import pandas as pd
import numpy as np

***series와 dataframe*

---

---

---

# **Series(열) 만드는 다양한 방법**
        pd.Series(data=None, index=None, dtype: Dtype, name=None,...)

## **List**

In [11]:
mylist = [1,2,3,'A',np.nan] #리스트를
s = pd.Series(data =mylist, index=range(5), name ="seq") #시리즈화한다.
s #인덱스 설정 안하면 알아서 잡힘..?

0      1
1      2
2      3
3      A
4    NaN
Name: seq, dtype: object

## **array**

**★array[[ ] , [ ]]  는 array타입이다. array로 감싸주면 array**

In [26]:
mylist = [1,2,3,'A',np.nan]
myarr = np.array(mylist) #np.array는 리스트를 배열화한 것이다.

myarr #array(['1', '2', '3', 'A', 'nan'], dtype='<U32')

print(myarr)#['1' '2' '3' 'A' 'nan']#array는 만들어서 쓰는게 아니라 리스트를 담아서 array화 시키는 것이다.
print(myarr.shape,"주의:1행 5열") #(5,) 배열에선 5열 1행 

['1' '2' '3' 'A' 'nan']
(5,) 주의:1행 5열


## **shape, len**

In [151]:
mylist = [[1,2,3],[10,20,30]]
print(mylist) #[[1, 2, 3], [10, 20, 30]]

myarr = np.array(mylist) #array로 배열화시킨 리스트
print(myarr)# [[ 1  2  3]
             #[10 20 30]]
    
print(myarr.shape)#mylist.shape는 안된다. 리스트는 쉐입이 아니라 len(list[])
#array의 shape = 2행, 3열

print("마이리스트의 리스트 갯수:",len(mylist), "마이리스트의 0번째 리스트의 갯수:",len(mylist[0]))


[[1, 2, 3], [10, 20, 30]]
[[ 1  2  3]
 [10 20 30]]
(2, 3)
마이리스트의 리스트 갯수: 2 마이리스트의 0번째 리스트의 갯수: 3


**★shape() : 함수 아님  
★mylist.shape : 에러 , list는 쉐입 없다. len으로 조회해야한다.  
★array의 shape는 (열,행) 이다. array(배열화)된 값들이 series화된다는 것은 배열화된 값이 가로에서 세로로로만 바뀐 것이기 때문에, array의 열값이 행으로 보이는 것**

In [12]:
mylist = [1,2,3,'A',np.nan]
myarr = np.array(mylist)
s = pd.Series(data = myarr, index=range(5), name ="seq") #어레이로 시리즈 만드는 법
s
print(s)
print(s.shape) #array로 만들었으니까 (5,)으로 shape이 조회된다.... array요소가 5개 있다.
#결국 배열화 전(리스트의 갯수(열값),리스트 안의 객체 값(행값))
print(len(s)) # row, 행 , record 갯수

0      1
1      2
2      3
3      A
4    nan
Name: seq, dtype: object
(5,)
5


---

---

---

# **Dataframe**

        *head(),tail(),describe(),shape()
        *data=None,
        index: Axes | None = None,
        columns: Axes | None = None,
        dtype: Dtype | None = None,

## **데이터프레임에 넣을 수 있는 것** : list / array /List + dict [ {} ]

In [13]:
mylist = [[1,2,3],[10,20,30]]
myarr = np.array(mylist)

# df = pd.DataFrame(data=myarr)
df = pd.DataFrame(data=mylist, columns=['a','b','c'],index = [10,20]) #떼거지는 무조건 []안에 넣기
print(df.shape)
print("row갯수:",len(df)) #row갯수


(2, 3)
row갯수: 2


## **List + dict [ {} ]**

**★dict에 사용된 키 값이 데이터프레임의 컬럼명이 된다.**

In [14]:
listdic = [{"uid":"kim","upw":111} ,
           {"uid":"kim","upw":111}] #딕셔너리를 리스트화한 것

df = pd.DataFrame(listdic) #딕셔너리에 사용된 키 값이 데이터프레임의 컬럼명이 되는 것
df
print(df)

   uid  upw
0  kim  111
1  kim  111


## **List + List [ [] ]**

In [83]:
listlist = [["kim",111] ,
           ["kim",111]] #리스트에 리스트(값만)

df = pd.DataFrame(listlist, columns = ['a','b']) # 컬럼명 따로 지정
df

a    b
0  kim  111
1  kim  111

---

---

---

---

# **데이터프레임 조회하기**

## df.info()

In [152]:
df.info() #해당하는 데이터프레임이 갖고있는 사이즈, 타입 등 정보 확인 용

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 10 to 20
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       2 non-null      int64
 1   b       2 non-null      int64
 2   c       2 non-null      int64
dtypes: int64(3)
memory usage: 64.0 bytes


## df.head()

In [52]:
df.head(1) #디폴트 5, 앞에서부터 값 꺼내와

a  b  c
10  1  2  3

## df.tail()

In [53]:
df.tail(1) #디폴트 5, 뒤에서부터 값 꺼내와

a   b   c
20  10  20  30

## df.describe()

In [55]:
df.describe() #값 요약 정보 보여줘

a          b          c
count   2.000000   2.000000   2.000000
mean    5.500000  11.000000  16.500000
std     6.363961  12.727922  19.091883
min     1.000000   2.000000   3.000000
25%     3.250000   6.500000   9.750000
50%     5.500000  11.000000  16.500000
75%     7.750000  15.500000  23.250000
max    10.000000  20.000000  30.000000

---

---

---

---

# **데이터프레임 구조 보기**

In [65]:
s= pd.Series([1,2,3,4])
df = pd.DataFrame(['a','b','c','d'], columns = ['code'])

df['seq'] = s # 시리즈에 값 넣기
df['sal'] = [100,200,300,400]
df[['id','pw']] = np.array([['kim',11]]*4)
#[]사이엔 값 하나만 넣는 것. 떼거지는 무조건  [] 묶기
df['tel'] = '000'
#df['tel'] = '010' 해당 키 값에 새 값을 넣으면 수정 
df

code  seq  sal   id  pw  tel
0    a    1  100  kim  11  000
1    b    2  200  kim  11  000
2    c    3  300  kim  11  000
3    d    4  400  kim  11  000

## **index 꺼내는 방법**

In [71]:
df = pd.DataFrame(['a','b','c','d'], columns = ['code'], index = [10,20,30,40]) #인덱스는 무조건 따라다닌다. 안보이게 안된다. 
df
#df.index 인덱스만 보이게
print(df.index)
print(df.index.values)
print(df.index.values.tolist()) #리스트화 하기

Int64Index([10, 20, 30, 40], dtype='int64')
[10 20 30 40]
[10, 20, 30, 40]


In [75]:
df = pd.DataFrame(['a','b','c','d'], columns = ['code'])
df.index = [10,20,30,40] # 인덱스는 밖으로 따로 빼서 부여해줘도 된다.
df

code
10    a
20    b
30    c
40    d

## **columns 꺼내는 방법**

In [6]:
s= pd.Series([1,2,3,4])
df = pd.DataFrame(['a','b','c','d'], columns = ['code'])
df['seq'] = s
df['sal'] = [100,200,300,400]
# df.columns #컬럼명만 떼오고싶다.

print(df)
df.values

  code  seq  sal
0    a    1  100
1    b    2  200
2    c    3  300
3    d    4  400


array([['a', 1, 100],
       ['b', 2, 200],
       ['c', 3, 300],
       ['d', 4, 400]], dtype=object)

In [79]:
s= pd.Series([1,2,3,4])
df = pd.DataFrame(['a','b','c','d'], columns = ['code'])
df['seq'] = s
df['sal'] = [100,200,300,400]
df.columns #컬럼명만 떼오고싶다.

print(df.columns)
print(df.columns.values)
print(df.columns.values.tolist()) #리스트화 하기, 인덱스나 컬럼이나 똑같다.

Index(['code', 'seq', 'sal'], dtype='object')
['code' 'seq' 'sal']
['code', 'seq', 'sal']


## **values 꺼내는 법**

In [80]:
s= pd.Series([1,2,3,4])
df = pd.DataFrame(['a','b','c','d'], columns = ['code'])
df['seq'] = s
df['sal'] = [100,200,300,400]

print(df.values)
print(df.values.tolist())

# 값 꺼내기

[['a' 1 100]
 ['b' 2 200]
 ['c' 3 300]
 ['d' 4 400]]
[['a', 1, 100], ['b', 2, 200], ['c', 3, 300], ['d', 4, 400]]


---

---

---

---

# **파일 꺼내오기**

## **pd.read_확장자("경로+파일명.확장자", sep="객체구분기준" )**

In [85]:
df = pd.read_csv("./lec08_emp.csv", sep=",") #구분자 sep 쓰든 안쓰든 디폴트는 ', 컴마' 이다.
df.head()

EMPNO   ENAME       JOB     MGR             HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0  1980-12-17 00:00:00   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20 00:00:00  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22 00:00:00  1250   500.0      30
3   7566   JONES   MANAGER  7839.0  1981-04-02 00:00:00  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28 00:00:00  1250  1400.0      30

## **숫자값에 nan이 있으면 데이터프레임 타입은 float 소숫점이 된다.**

In [86]:
df.info() #nan 있는 열만 Dtype가 float64로 조회

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   EMPNO     14 non-null     int64  
 1   ENAME     14 non-null     object 
 2   JOB       14 non-null     object 
 3   MGR       13 non-null     float64
 4   HIREDATE  14 non-null     object 
 5   SAL       14 non-null     int64  
 6   COMM      4 non-null      float64
 7   DEPTNO    14 non-null     int64  
dtypes: float64(2), int64(3), object(3)
memory usage: 1.0+ KB


In [89]:
df = pd.read_csv("./lec08_emp.csv", sep=",", parse_dates =['HIREDATE'])
#해당 컬럼을 날짜 형태로, 안하면(위에 지저분한 데이터값 보기) 나중에 또 변환해야한다.

df.head(13) # 데이터 과부하 막기 위해 항상 df(변수)만 불러오는게 아닌, head나 tail 습관화하자.

EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0 1980-12-17   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0 1981-02-22  1250   500.0      30
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850     NaN      30
6    7782     CCC    MANAGER  7839.0 1981-06-09  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0 1987-07-13  3000     NaN      20
8    7839    KING  PRESIDENT     NaN 1981-11-17  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0 1981-09-08  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0 1987-07-13  1100     NaN      20
11   7900   JAMES      CLERK  7698.0 1981-12-03   950     NaN      30
12   7902    FORD    ANALYST  7566.0 1981-12-03  3000     NaN      20

In [91]:
df.info() #entry : 총 데이터 건수 (총 열값 알 수 있다.)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   EMPNO     14 non-null     int64         
 1   ENAME     14 non-null     object        
 2   JOB       14 non-null     object        
 3   MGR       13 non-null     float64       
 4   HIREDATE  14 non-null     datetime64[ns]
 5   SAL       14 non-null     int64         
 6   COMM      4 non-null      float64       
 7   DEPTNO    14 non-null     int64         
dtypes: datetime64[ns](1), float64(2), int64(3), object(2)
memory usage: 1.0+ KB


# **결측(missing value)처리**
* np.nan

* df1.dropna(axis =1 또는 axis=0) : 지우기 
* df1.fillna(값) : 채우기
* pd.isna(df1) : 널값 찾기

In [18]:
dfcp = df.copy()
dfcp

code  seq  sal
0    a    1  100
1    b    2  200
2    c    3  300
3    d    4  400

* <font color=red><b> 숫자값에 nan이 있으면 타입은 float(소숫점)

## **Dropna()** : 결측을 버리는 것

* axis = 0 : 결측이 있는 행을 지운다.
* axis = 1 : 결측이 있는 열을 지운다.

In [118]:
dfcp.dropna() #결측 지워라
dfcp.dropna(axis=0)
# dfcp.dropna(axis=0, inplace = True) #교체 명령어를 실행하면 변수 재정의랑 같은 의미이다.
dfcp

EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0 1981-02-22  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500     0.0      30

**★드롭 후 dfcp(변수)를 재정의해줘야 메모리상에서가 아닌 실제로 지워진다.**

In [22]:
dfcp = df.copy()

dfcp = dfcp.dropna(axis=1)
dfcp

code  seq  sal
0    a    1  100
1    b    2  200
2    c    3  300
3    d    4  400

## **fillna()** : 결측을 채우는 것

* 결측 채우기 후 일반적으로 형변환을 한다. (int)
* df['컬럼'] = df['컬럼'].astype('int')

In [21]:
dfcp = df.copy()
dfcp.fillna(9999)

dfcp = dfcp.fillna(9999) #변수 재정의 or inplace

## **n개의 컬럼 지정하여 값 넣기**

In [24]:
dfcp = df.copy()
dfcp[['COMM','MGR']] = dfcp[['COMM','MGR']].fillna(2222) # n개의 컬럼값 지정하기. 떼거지는 []묶기
# dfcp['COMM'] = dfcp['COMM'].fillna(8888) #각 컬럼별로 결측값 지정하기
# dfcp['MGR'] = dfcp['MGR'].fillna(77)

dfcp[['COMM','MGR']] = dfcp[['COMM','MGR']].astype('int') #결측 채우기 후, 보통 소숫점으로 바뀌는 값을 다시 int로 형변환을 한다. 
dfcp

KeyError: "None of [Index(['COMM', 'MGR'], dtype='object')] are in the [columns]"

In [23]:
dfcp.isna().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of     code    seq    sal
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False>

## **isna(df1)** : 결측 판단

* df.isna()
* pd.isna(df1)

In [8]:
dfcp = df.copy()
# pd.isna(dfcp)

# dfcp.isna()
# pd.notna(dfcp)
# pd.isnull(dfcp)
# pd.notnull(dfcp)

In [99]:
pd.isna(df)

EMPNO  ENAME    JOB    MGR  HIREDATE    SAL   COMM  DEPTNO
0   False  False  False  False     False  False   True   False
1   False  False  False  False     False  False  False   False
2   False  False  False  False     False  False  False   False
3   False  False  False  False     False  False   True   False
4   False  False  False  False     False  False  False   False
5   False  False  False  False     False  False   True   False
6   False  False  False  False     False  False   True   False
7   False  False  False  False     False  False   True   False
8   False  False  False   True     False  False   True   False
9   False  False  False  False     False  False  False   False
10  False  False  False  False     False  False   True   False
11  False  False  False  False     False  False   True   False
12  False  False  False  False     False  False   True   False
13  False  False  False  False     False  False   True   False

---

---

---

# SELECT in DataFrame

* **loc[줄,칸]** : 값 으로 꺼내기
* **ioc[줄,칸]** : index로 꺼내기

* [줄,칸]에 들어갈 수 있는 값
    - 단일값
    - [단일값,단일값,단일값]
    - 슬라이싱[ : ]